### ISSUE TITLE
Unity2019.2 + abandoned API "unityplayer. Start();" And "unityplayer. Stop();"

### ISSUE THREAD

**Issue by libaibaba** [dbeef/CreatingAndroidLiveWallpapers#3]
Unity2019.2 + abandoned API "unityplayer. Start();" And "unityplayer. Stop();"
![`F$R@J{6}6ABU3(@%1A9IBT](https://user-images.githubusercontent.com/52236285/118775676-c516d300-b8b9-11eb-8d6f-7e17ad152fc7.png)

**Comment by dbeef** [comment]
Hello @libaibaba, I will investigate it this weekend. In the meantime, please keep this issue updated if you find a workaround. Regards, Daniel.

**Comment by libaibaba** [comment]
I'm very sorry, I compromised with unity, I'm using 2019.1.14f1.

**Comment by libaibaba** [comment]
But I think it might have something to do with that.
![Uploading B0QH%V0203E)ZTX)[[Y@1LG.png…]()
![Uploading S5UE6@CI4~UA7UAS1M`2F5F.png…]()
![Uploading SQ8M62H)L@[Z{R7BJNHS))Q.png…]()

**Comment by libaibaba** [comment]
But I think it might have something to do with that.
![B0QH%V0203E)ZTX) Y@1LG](https://user-images.githubusercontent.com/52236285/119256500-9d927400-bbf3-11eb-8f6a-1b942a6fd757.png)
![S5UE6@CI4~UA7UAS1M`2F5F](https://user-images.githubusercontent.com/52236285/119256504-9f5c3780-bbf3-11eb-8354-034d0c69d13f.png)
![SQ8M62H)L@ Z{R7BJNHS))Q](https://user-images.githubusercontent.com/52236285/119256506-a08d6480-bbf3-11eb-92bd-ea1b7eb2a8c4.png)

**Comment by libaibaba** [comment]
[https://issuetracker.unity3d.com/issues/android-crash-when-using-unityplayer-getapplicationcontext-this-on-exported-andoid-projects](url)    Helpful?

**Comment by libaibaba** [comment]
[https://docs.unity3d.com/ja/2023.2/Manual/UpgradeGuide20231.html#android-unityplayer]Upgrade to Unity 2023.1 and using replace **UnityPlayer**  to **UnityPlayerForActivityOrService** ，**mUnityPlayer.lowMemory();** to **mUnityPlayer.onTrimMemory(UnityPlayerForActivityOrService.MemoryUsage.Low);**  No need to do anything else，**!!! If your project does not have a script , Do not use mUnityPlayer.UnitySendMessage( ), which will cause Cause: null pointer dereference**
